[profile.release]
panic = "unwind"

[workspace]
members = [
	#"node",
	#"pallets/*",
	#"runtime/vane-parachain-runtime",
	"runtime/vane-container-runtime"
]
resolver = "2"

[patch.crates-io]
sp-io = { git = "https://github.com/moondance-labs/polkadot-sdk", branch = "tanssi-polkadot-v1.1.0" }
