[settings]
bootnode = false

[relaychain]
chain = "rococo-local"
default_command = "../bin/polkadot"
bootnode = false

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 8000

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  ws_port = 8050

[[parachains]]
id = 2000
#chain_spec_path = "./tmp1/vane.json"
cumulus_based = true
onboard_as_parachain = true

	[[parachains.collators]]
	name = "vane-collator"
	ws_port = 9910
	command = "./target/release/vane-node"
#	args = [ "-lxcm=trace", "--state-cache-size=0" ]
