[settings]
bootnode = false

[relaychain]
chain = "polkadot"
default_command = "../bin/polkadot"
chain_spec_path = "../../polkadot/tmp01/rococo-local.json"
bootnode = false

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

# [[parachains]]
# id = 2000
# chain = "vane"
# addToGenesis = false
# cumulus_based = true
# chain_spec_path = "tmp1/vane.json"
# bootnode = false
# onboard_as_parachain = true
# register_para = true

#   [[parachains.collator_groups]]
#     count = 1
#     # onboard_as_parachain = true
#     # register_para = true

#     [parachains.collator_groups.collator]
#       name = "vane-collator1"
#       command = "./target/release/vane-node"
#       genesis_wasm_path = "tmp1/vane-wasm"
#       genesis_state_path = "tmp1/vane-state"

  # [parachains.collator]
  # name = "vane-collator1"
  # command = "./target/release/vane-node"
  # genesis_wasm_path = "tmp1/vane-wasm"
  # genesis_state_path = "tmp1/vane-state"
  # onboard_as_parachain = true
  # register_para = true
  
  # [parachains.collator_groups]
  # onboard_as_parachain = true
  # register_para = true



